FROM ubuntu

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    git \
    python3-pip \
    python-setuptools \
    python-dev-is-python3 \
  && rm -rf /var/lib/apt/lists/*
  
RUN apt-get update\
  && apt-get install -y python3.10-venv

RUN pip3 install --upgrade pip
RUN pip3 install 'ipython<6'
RUN rm -rf /var/lib/apt/lists/*


RUN mkdir /app

RUN mkdir /app/api_consumer

RUN chmod -R 777 /app/

COPY setup_on_ubuntu_docker.sh /app/setup_on_ubuntu_docker.sh

COPY ./ /app/api_consumer


VOLUME /app
WORKDIR /app


RUN pip3 install -r /app/api_consumer/requirements.txt

RUN pip3 install jupyter
RUN rm -rf /var/lib/apt/lists/*


EXPOSE 8888
EXPOSE 5000


CMD /app/setup_on_ubuntu_docker.sh
